export const searchData = {
    a: [],
    b: ['Bewajah - Sanam Teri Kasam', 'Be Intehaan - Race 2', 'Badtameez Dil - Yeh Jawaani Hai Dewaani'],
    c: [],
    d: [],
    e: [],
    f: [],
    g: [],
    h: [],
    i: [],
    j: [],
    k: [],
    l: [],
    m: [],
    n: [],
    o: [],
    p: [],
    q: [],
    r: [],
    s: [],
    t: [],
    u: [],
    v: [],
    w: [],
    x: [],
    y: [],
    z: []
};
